# Generated by Django 5.1.7 on 2025-04-09 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('air_date', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_number', models.PositiveIntegerField()),
                ('air_date', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('still', models.URLField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tvshows.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('backdrop', models.URLField(blank=True, null=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('is_anime', models.BooleanField(default=False)),
                ('countries', models.ManyToManyField(to='custom_auth.country')),
                ('genres', models.ManyToManyField(to='custom_auth.genre')),
                ('keywords', models.ManyToManyField(to='custom_auth.keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tvshows.tvshow'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('show', 'season_number')},
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='tvshows.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_date'],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
