# Generated by Django 5.2 on 2025-04-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_tvshow_added_by_tvshow_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EpisodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poster', models.URLField(blank=True, null=True)),
                ('episodes', models.ManyToManyField(related_name='episode_groups', to='tvshows.episode')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_groups', to='tvshows.tvshow')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
