# Generated by Django 5.2 on 2025-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_tvshow_imdb_id_episodegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodegroup',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
