# Generated by Django 5.2 on 2025-04-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_episodegroup_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodegroup',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='episodegroup',
            name='poster',
        ),
        migrations.CreateModel(
            name='EpisodeSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poster', models.URLField(blank=True, null=True)),
                ('episodes', models.ManyToManyField(related_name='sub_groups', to='tvshows.episode')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='tvshows.episodegroup')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
