# Generated by Django 5.2 on 2025-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0005_remove_episodegroup_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodegroup',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='episodesubgroup',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
