# Generated by Django 5.2 on 2025-04-24 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0008_alter_episodesubgroup_tmdb_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchedepisode',
            index=models.Index(fields=['user', 'episode'], name='tvshows_wat_user_id_18b490_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedepisode',
            index=models.Index(fields=['watched_date'], name='tvshows_wat_watched_2b1de2_idx'),
        ),
    ]
