# Generated by Django 5.2 on 2025-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_productioncompany'),
        ('tvshows', '0009_watchedepisode_tvshows_wat_user_id_18b490_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='production_companies',
            field=models.ManyToManyField(to='custom_auth.productioncompany'),
        ),
    ]
