# Generated by Django 5.2.5 on 2025-11-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0010_tvshow_production_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tvdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='tvdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
