# Generated by Django 5.2.5 on 2025-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0011_episode_tvdb_id_tvshow_tvdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='air_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
