# Generated by Django 6.0.2 on 2026-03-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_mediaperson_custom_auth_content_6064fc_idx_and_more'),
        ('tvshows', '0012_episode_air_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['air_date'], name='tvshows_epi_air_dat_8f6bca_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'air_date'], name='tvshows_epi_season__8856b3_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(condition=models.Q(('tmdb_id__isnull', False)), fields=['tmdb_id'], name='episode_tmdb_id_partial'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(condition=models.Q(('tvdb_id__isnull', False)), fields=['tvdb_id'], name='episode_tvdb_id_partial'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(condition=models.Q(('tmdb_id__isnull', False)), fields=['tmdb_id'], name='season_tmdb_id_partial'),
        ),
        migrations.AddIndex(
            model_name='tvshow',
            index=models.Index(fields=['status', 'date_updated'], name='tvshows_tvs_status_0505d8_idx'),
        ),
    ]
