# Generated by Django 6.0.2 on 2026-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0013_episode_tvshows_epi_air_dat_8f6bca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
