version: '3.8'

services:
  web:
    build:
      context: ./entertainment
      dockerfile: Dockerfile.dev
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./entertainment:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - webnet

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  redis_data_dev:
  postgres_data_dev: