# Generated by Django 5.1.7 on 2025-04-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('musicbrainz_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('ep', 'EP'), ('soundtrack', 'Soundtrack'), ('compilation', 'Compilation'), ('score', 'Score'), ('other', 'Other')], default='album', max_length=20)),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_albums', to='custom_auth.person')),
                ('genres', models.ManyToManyField(blank=True, to='custom_auth.genre')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_albums', to='custom_auth.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAlbumRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('relationship_type', models.CharField(choices=[('soundtrack', 'Soundtrack'), ('score', 'Original Score'), ('inspired_by', 'Inspired By Media'), ('featured_in', 'Featured In Media'), ('promotional', 'Promotional Album'), ('opening_theme', 'Opening Theme'), ('ending_theme', 'Ending Theme'), ('other', 'Other Relationship')], default='soundtrack', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Media-Album Relationship',
                'verbose_name_plural': 'Media-Album Relationships',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='music_media_content_588483_idx')],
                'unique_together': {('content_type', 'object_id', 'album')},
            },
        ),
    ]
