# Generated by Django 6.0.2 on 2026-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='original_title',
            field=models.CharField(max_length=255),
        ),
    ]
