services:
  django:
    loadbalancer:
      servers:
        - url: "http://django:8000"
  
http:
  routers:
    django:
      rule: "Host(`your-actual-domain.com`)"  # Replace with your actual domain
      service: django
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      middlewares:
        - redirect-to-https
    
    # Define as many domain routes as needed for your application
    entertainment:
      rule: "Host(`your-actual-domain.com`)"  # Use your production domain
      service: entertainment
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      middlewares:
        - redirect-to-https

  services:
    django:
      loadBalancer:
        servers:
          - url: "http://django:8000"
    
    entertainment:
      loadBalancer:
        servers:
          - url: "http://web:8000"  # Should match your docker-compose.yml service name

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https"
        permanent: true

    # Add security headers for production
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000  # 1 year
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"