http:
  routers:
    entertainment:
      rule: "Host(`${DOMAIN:-your-actual-domain.com}`)"
      service: entertainment
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      middlewares:
        - redirect-to-https

    api:
      rule: "Host(`${DOMAIN:-your-actual-domain.com}`) && PathPrefix(`/dashboard`)"
      service: "api@internal"
      entrypoints:
        - websecure
      middlewares:
        - auth
      tls:
        certResolver: myresolver

  services:
    entertainment:
      loadBalancer:
        servers:
          - url: "http://web:8000"  # Matches your docker-compose service name

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https"
        permanent: true

    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000  # 1 year
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"

    auth:
      basicAuth:
        users:
          # Generate these with: htpasswd -nb admin secure_password
          # The below is example only - replace with your own credentials!
          - "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/"  

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"