providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Secure dashboard configuration
api:
  dashboard: true  # Enable the dashboard
  insecure: false  # Ensure it's not running in insecure mode

log:
  level: "INFO"  # Use INFO or WARNING for production

accessLog: {}  # Enables access logs with default settings

certificatesResolvers:
  myresolver:
    acme:
      email: your-actual-email@example.com  # Use a real email for Let's Encrypt notifications
      storage: /acme.json
      httpChallenge:
        entryPoint: web