# Generated by Django 5.2.5 on 2025-10-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationpreference_quiet_hours_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='review_replies',
        ),
    ]
