# Generated by Django 5.2.5 on 2025-10-16 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_remove_notificationpreference_review_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('new_release', 'New Release'), ('watchlist_update', 'Watchlist Update'), ('recommendation', 'Recommendation'), ('system', 'System Notification')], max_length=50),
        ),
        migrations.CreateModel(
            name='QueuedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('icon', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queued_notifications',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'is_sent'], name='queued_noti_user_id_35fda8_idx'), models.Index(fields=['is_sent', 'created_at'], name='queued_noti_is_sent_a0016c_idx')],
            },
        ),
    ]
