# Generated by Django 5.2.5 on 2025-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationlog_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='movie_of_week',
            field=models.BooleanField(default=True, help_text='Community Movie of the Week reminders'),
        ),
    ]
