# Generated by Django 5.2.5 on 2025-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_movie_of_week_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='new_reviews',
            field=models.BooleanField(default=True, help_text='Notify when someone reviews items in your watchlist'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('new_release', 'New Release'), ('watchlist_update', 'Watchlist Update'), ('recommendation', 'Recommendation'), ('new_review', 'New Review'), ('system', 'System Notification')], max_length=50),
        ),
    ]
