# Generated by Django 5.2.5 on 2025-11-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreference_new_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='new_reviews',
            field=models.BooleanField(default=True, help_text='Notify when users post reviews'),
        ),
    ]
