# Generated by Django 5.2.8 on 2025-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='igdb_id',
            new_name='rawg_id',
        ),
        migrations.AddField(
            model_name='game',
            name='backdrop',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
