# Generated by Django 6.0 on 2025-12-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamegenre_platform_game_keywords_game_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('rawg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('image_background', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('rawg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('image_background', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('rawg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('image_background', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.gamecollection'),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, to='games.gamedeveloper'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='games.gamepublisher'),
        ),
    ]
