# Generated by Django 6.0 on 2025-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamecollection_gamedeveloper_gamepublisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='collection',
            new_name='game_collection',
        ),
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developed_games', to='games.gamedeveloper'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='published_games', to='games.gamepublisher'),
        ),
    ]
