# Generated by Django 5.1.7 on 2025-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaperson',
            name='character_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
