# Generated by Django 5.2 on 2025-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_mediaperson_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
