# Generated by Django 5.1.7 on 2025-03-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_keyword_person_imdb_id_person_tmdb_id'),
        ('movies', '0002_movie_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
