# Generated by Django 5.2 on 2025-04-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0004_person_wikidata_id'),
        ('tvshows', '0003_tvshow_imdb_id_episodegroup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_with_season',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_without_season',
        ),
        migrations.AddField(
            model_name='review',
            name='episode_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvshows.episodegroup'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'season', 'episode_group'), name='unique_review_with_season_or_group'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('season__isnull', True), ('episode_group__isnull', True)), fields=('user', 'content_type', 'object_id'), name='unique_review_without_season_or_group'),
        ),
    ]
