# Generated by Django 5.2 on 2025-04-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0005_remove_review_unique_review_with_season_and_more'),
        ('tvshows', '0006_alter_episodegroup_tmdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_with_season_or_group',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_without_season_or_group',
        ),
        migrations.RemoveField(
            model_name='review',
            name='episode_group',
        ),
        migrations.AddField(
            model_name='review',
            name='episode_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvshows.episodesubgroup'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'season', 'episode_subgroup'), name='unique_review_with_season_or_subgroup'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('season__isnull', True), ('episode_subgroup__isnull', True)), fields=('user', 'content_type', 'object_id'), name='unique_review_without_season_or_subgroup'),
        ),
    ]
