# Generated by Django 5.1.7 on 2025-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
