# Generated by Django 5.1.7 on 2025-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_person_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_composer',
            field=models.BooleanField(default=False),
        ),
    ]
