# Generated by Django 5.2 on 2025-04-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_remove_review_unique_review_with_season_or_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_keywords', models.BooleanField(default=True, help_text='Show keywords in media details')),
                ('show_review_text', models.BooleanField(default=True, help_text='Show review text in media details')),
                ('show_plot', models.BooleanField(default=True, help_text='Show plot in media details')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
