# Generated by Django 5.1.7 on 2025-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_person_is_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='genre_icons/'),
        ),
    ]
