# Generated by Django 5.2 on 2025-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
    ]
