# Generated by Django 5.1.7 on 2025-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_genre_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.URLField()),
                ('backdrop', models.URLField()),
                ('release_date', models.DateField()),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('runtime', models.IntegerField()),
                ('rating', models.FloatField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('is_anime', models.BooleanField(default=False)),
                ('cast', models.ManyToManyField(blank=True, limit_choices_to={'is_actor': True}, related_name='cast', to='custom_auth.person')),
                ('composer', models.ManyToManyField(blank=True, limit_choices_to={'is_composer': True}, related_name='sound', to='custom_auth.person')),
                ('countries', models.ManyToManyField(to='custom_auth.country')),
                ('directors', models.ManyToManyField(blank=True, limit_choices_to={'is_director': True}, related_name='directors', to='custom_auth.person')),
                ('genres', models.ManyToManyField(to='custom_auth.genre')),
                ('keywords', models.ManyToManyField(to='custom_auth.keyword')),
                ('producers', models.ManyToManyField(blank=True, limit_choices_to={'is_producer': True}, related_name='producers', to='custom_auth.person')),
                ('writers', models.ManyToManyField(blank=True, limit_choices_to={'is_writer': True}, related_name='writers', to='custom_auth.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
