# Generated by Django 5.2 on 2025-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_productioncompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hardcover_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
