# Generated by Django 5.1.7 on 2025-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_rename_is_composer_person_is_original_music_composer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='movie_backdrops/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='person_profiles/'),
        ),
    ]
