# Generated by Django 5.2 on 2025-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_person_hardcover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_book_author',
            field=models.BooleanField(default=False),
        ),
    ]
