# Generated by Django 5.2 on 2025-05-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_enable_pg_trgm'),
        ('custom_auth', '0012_person_is_book_author'),
    ]

    operations = [
    ]
