# Generated by Django 5.1.7 on 2025-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_season_episode_tvshow_season_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_actor',
            field=models.BooleanField(default=False),
        ),
    ]
