# Generated by Django 5.2.1 on 2025-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_merge_0002_enable_pg_trgm_0012_person_is_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_backgrounds/'),
        ),
    ]
