# Generated by Django 5.1.7 on 2025-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0014_person_is_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['content_type', 'object_id'], name='custom_auth_content_33d146_idx'),
        ),
    ]
