# Generated by Django 5.2.1 on 2025-05-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_genre_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='icon',
        ),
    ]
