# Generated by Django 5.2.5 on 2025-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_remove_genre_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
