# Generated by Django 5.1.7 on 2025-04-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_alter_watchlist_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
