# Generated by Django 5.2.5 on 2025-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0016_keyword_igdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='igdb_id',
        ),
    ]
