# Generated by Django 5.1.7 on 2025-04-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_alter_review_unique_together_review_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_band_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_musician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_performer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_songwriter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='album_backdrops/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('musicbrainz_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('ep', 'EP'), ('soundtrack', 'Soundtrack'), ('compilation', 'Compilation'), ('score', 'Score'), ('other', 'Other')], default='album', max_length=20)),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_albums', to='custom_auth.person')),
                ('genres', models.ManyToManyField(blank=True, to='custom_auth.genre')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_albums', to='custom_auth.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieAlbumRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('soundtrack', 'Soundtrack'), ('score', 'Original Score'), ('inspired_by', 'Inspired By Movie'), ('featured_in', 'Featured In Movie'), ('promotional', 'Promotional Album'), ('other', 'Other Relationship')], default='soundtrack', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.album')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.movie')),
            ],
            options={
                'verbose_name': 'Movie-Album Relationship',
                'verbose_name_plural': 'Movie-Album Relationships',
                'unique_together': {('movie', 'album')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='related_movies',
            field=models.ManyToManyField(blank=True, related_name='related_albums', through='custom_auth.MovieAlbumRelationship', to='custom_auth.movie'),
        ),
    ]
