# Generated by Django 5.2.8 on 2025-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_remove_keyword_igdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
