# Generated by Django 6.0 on 2025-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
