# Generated by Django 5.1.7 on 2025-04-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0019_movie_imdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='poster',
            new_name='cover',
        ),
    ]
