# Generated by Django 5.1.7 on 2025-04-05 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0020_rename_poster_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='related_movies',
        ),
        migrations.CreateModel(
            name='MediaAlbumRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('relationship_type', models.CharField(choices=[('soundtrack', 'Soundtrack'), ('score', 'Original Score'), ('inspired_by', 'Inspired By Media'), ('featured_in', 'Featured In Media'), ('promotional', 'Promotional Album'), ('opening_theme', 'Opening Theme'), ('ending_theme', 'Ending Theme'), ('other', 'Other Relationship')], default='soundtrack', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.album')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Media-Album Relationship',
                'verbose_name_plural': 'Media-Album Relationships',
            },
        ),
        migrations.DeleteModel(
            name='MovieAlbumRelationship',
        ),
        migrations.AddIndex(
            model_name='mediaalbumrelationship',
            index=models.Index(fields=['content_type', 'object_id'], name='custom_auth_content_0e5b01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaalbumrelationship',
            unique_together={('content_type', 'object_id', 'album')},
        ),
    ]
