# Generated by Django 6.0.2 on 2026-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_auth', '0020_meme'),
        ('tvshows', '0012_episode_air_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mediaperson',
            index=models.Index(fields=['content_type', 'object_id'], name='custom_auth_content_6064fc_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaperson',
            index=models.Index(fields=['content_type', 'object_id', 'role'], name='custom_auth_content_ae0c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'object_id'], name='custom_auth_content_2c6f00_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='custom_auth_user_id_e4e0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'date_added'], name='custom_auth_content_076301_idx'),
        ),
    ]
