# Generated by Django 5.1.7 on 2025-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_remove_album_related_movies_mediaalbumrelationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='backdrop',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
