# Generated by Django 5.1.7 on 2025-04-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_remove_album_backdrop_alter_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_band_member',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_performer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_songwriter',
        ),
    ]
