# Generated by Django 6.0.2 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_person_openlibrary_id_alter_hardcover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='hardcover_tag_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
