# Generated by Django 5.1.7 on 2025-04-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0024_movie_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
