# Generated by Django 5.1.7 on 2025-04-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0025_delete_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date_reviewed',
            new_name='date_added',
        ),
    ]
