# Generated by Django 6.1.1 on 2026-09-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_watchlistevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchlistevent',
            new_name='custom_auth_user_id_29a684_idx',
            old_name='custom_auth_user_id_ct_date_idx',
        ),
    ]
