# Generated by Django 6.0.2 on 2026-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0027_rename_custom_auth_user_id_ct_date_idx_custom_auth_user_id_29a684_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('view_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(db_index=True)),
                ('db_time_ms', models.PositiveIntegerField()),
                ('query_count', models.PositiveIntegerField()),
                ('repeated_query', models.TextField(blank=True)),
                ('repeated_query_count', models.PositiveIntegerField(default=0)),
                ('slowest_queries', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
