# Generated by Django 5.1.7 on 2025-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_keyword_person_imdb_id_person_tmdb_id'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(to='custom_auth.keyword'),
        ),
    ]
