# Generated by Django 5.2 on 2025-05-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOfWeekPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_reason', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_week_suggestions', to=settings.AUTH_USER_MODEL)),
                ('watched_by', models.ManyToManyField(blank=True, related_name='movies_of_week_watched', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'date_created'],
            },
        ),
    ]
