# Generated by Django 5.1.7 on 2025-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_review_is_movie_review_movie'),
        ('movies', '0002_movie_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_anime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, related_name='cast', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, related_name='directors', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, null=True, related_name='producers', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, null=True, related_name='writers', to='custom_auth.person'),
        ),
    ]
