# Generated by Django 5.2 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_productioncompany'),
        ('movies', '0003_movieofweekpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='custom_auth.productioncompany'),
        ),
    ]
