# Generated by Django 5.1.7 on 2025-03-20 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_person_date_of_birth'),
        ('movies', '0003_movie_is_anime_alter_movie_cast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrops',
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='cast', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directors', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='producers', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='writers', to='custom_auth.person'),
        ),
    ]
