# Generated by Django 5.2 on 2025-05-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_trigram_indexes'),
        ('movies', '0004_movie_production_companies'),
    ]

    operations = [
    ]
