# Generated by Django 6.0.2 on 2026-03-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_mediaperson_custom_auth_content_6064fc_idx_and_more'),
        ('movies', '0005_merge_20250525_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', 'release_date'], name='movies_movi_status_66fc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['date_updated'], name='movies_movi_date_up_f74d57_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['collection', 'release_date'], name='movies_movi_collect_389251_idx'),
        ),
        migrations.AddIndex(
            model_name='movieofweekpick',
            index=models.Index(fields=['status', 'date_created'], name='movies_movi_status_67e148_idx'),
        ),
    ]
