# Generated by Django 5.1.7 on 2025-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_person_is_composer'),
        ('movies', '0005_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='composer',
            field=models.ManyToManyField(blank=True, related_name='sound', to='custom_auth.person'),
        ),
    ]
