# Generated by Django 5.1.7 on 2025-03-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_genre_icon'),
        ('movies', '0007_alter_movie_cast_alter_movie_composer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actor': True}, related_name='cast', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='composer',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_composer': True}, related_name='sound', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_director': True}, related_name='directors', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_producer': True}, related_name='producers', to='custom_auth.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_writer': True}, related_name='writers', to='custom_auth.person'),
        ),
    ]
