# Generated by Django 5.1.7 on 2025-04-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_added_by_movie_added_on_movie_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
