# Generated by Django 5.1.7 on 2025-04-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_backdrop_alter_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_on',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='updated_on',
            new_name='date_updated',
        ),
    ]
