name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  merge-to-production:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Merge main to prod
        run: |
          git checkout prod || git checkout -b prod
          git merge --ff-only main
          git push origin prod

  deploy-to-vps:
    needs: merge-to-production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/your/entertainment-list
            git fetch
            git checkout production
            git pull origin production
            
            # Handle environment file if needed
            # cp /path/to/production.env .env
            
            # Rebuild and restart containers
            docker-compose down
            docker-compose up -d --build
            
            # Run migrations
            docker-compose exec -T web python manage.py migrate
            
            # Collect static files (if needed)
            docker-compose exec -T web python manage.py collectstatic --noinput